version: '3'

services:
  person-service:
    image: image3
    ports:
      - "8080:8080"
    environment:
      - DB_IP=host.docker.internal
    networks:
      demo_net:
        aliases:
          - person-service

networks:
  demo_net:
    external: true